### ISSUE TITLE
Fiddler会漏抓微信公众号历史文章

### ISSUE THREAD

**Issue by JohnGuoy** [LeLe86/vWeChatCrawl#16]
你的教程文章里说“打开公众号历史文章列表之后，在列表中不断下划，使历史文章列表都显示出来，但注意不要划得太快”，我已经划得很慢了，大概1秒钟划一下，Fiddler还是会漏抓，有什么解决方法吗？

软件我用的是从你的教程文章里下载的版本，微信我用的是2.9.5版本，有历史文章界面

**Comment by LeLe86** [comment]
请列举出：哪个公众号，划到第多少条的时候漏抓，请列出你发现漏抓的对比截图。另外，1秒1次是个“非常快”的速度。
